name: auto-merge

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: major
          github-token: ${{ secrets.GITHUB_TOKEN }}
